// <auto-generated />
using System;
using FlightSearch_Repolayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightSearch_Repolayer.Migrations
{
    [DbContext(typeof(Depotcontext))]
    [Migration("20220517170047_initial211")]
    partial class initial211
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Flight_Entities.Class2", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Business");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<string>("Flight_number")
                        .IsRequired();

                    b.Property<string>("From_Place");

                    b.Property<string>("Instrumentused");

                    b.Property<string>("Scheduledays");

                    b.Property<DateTime>("Startdatetime");

                    b.Property<string>("To_Place");

                    b.Property<int>("cost");

                    b.Property<string>("isActive");

                    b.Property<string>("meal");

                    b.Property<int>("non_business");

                    b.Property<int>("rows");

                    b.HasKey("id");

                    b.HasIndex("Flight_number");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Flight_Entities.Flight", b =>
                {
                    b.Property<string>("Flightno");

                    b.Property<string>("Airline");

                    b.HasKey("Flightno");

                    b.ToTable("Flights_header");
                });

            modelBuilder.Entity("Flight_Entities.Class2", b =>
                {
                    b.HasOne("Flight_Entities.Flight", "Fligt_no")
                        .WithMany()
                        .HasForeignKey("Flight_number")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
